### ISSUE TITLE
Working cannon reports

### ISSUE THREAD

**Issue by TylerS1066** [TylerS1066/Movecraft-Cannons#11]
I'm opening this issue so people can report fully working Movecraft-Cannons installs.  This will allow us to compare these reports to #9 and #10 to find the differences and track down these annoying bugs,

**Comment by galacticwarrior9** [comment]
I think I managed to get a working version, but it required making a [fork of Movecraft-Cannons](https://github.com/CCNetMC/Movecraft-Cannons) and Movecraft itself with a few changes

One problem with cannon rotation was that the `CraftRotateEvent` could be cancelled by other plugins with listeners operating at a higher priority. As a result, Movecraft-Cannons would rotate the cannons data even though the craft itself was ultimately prevented from rotating. To resolve this, the CraftRotateEvent listener was set to run at `EventPriority.MONITOR` with `ignoreCancelled` set to `true`.

With translation, I think the problems stemmed from the use of `CraftPreTranslateEvent`:
* The craft may be prevented from moving if `CraftTranslateEvent` is cancelled, which is fired after `CraftPreTranslateEvent`. As a result, the data of the cannons is translated while the craft itself is not.
* It looks like displacement of the craft may be modified after `CraftPreTranslateEvent` is called (e.g. the y displacement [here](https://github.com/APDevTeam/Movecraft/blob/main/modules/Movecraft/src/main/java/net/countercraft/movecraft/async/translation/TranslationTask.java#L201), if I'm understanding this correctly), so there could be a discrepancy between how much Movecraft-Cannons translates the cannons data by and how much the craft translates in reality. To resolve this, I added a new `CraftPostTranslateEvent` event to Movecraft, which is exactly like `CraftPreTranslateEvent` but is only fired after translation has occurred.

Another change I made was caching the cannons of each craft after detection, rather than trying to find them at the translation stage. I don't know if that particularly helped, but it was a nice performance booster

**Comment by TylerS1066** [comment]
> One problem with cannon rotation was that the `CraftRotateEvent` could be cancelled by other plugins with listeners operating at a higher priority. As a result, Movecraft-Cannons would rotate the cannons data even though the craft itself was ultimately prevented from rotating. To resolve this, the CraftRotateEvent listener was set to run at `EventPriority.MONITOR` with `ignoreCancelled` set to `true`.

This is a good point, thank you for letting me know.


> With translation, I think the problems stemmed from the use of `CraftPreTranslateEvent`

Hmm, that is a good point.  I'm going to ask CC if there is a proper method to do this in the current API, or if we need to expand the API as you suggest.

**Comment by TylerS1066** [comment]
Since there have been no reports of problems in 3 months, I am going to mark this as resolved!
